name: run-tests

on:
    workflow_run:
        workflows: ['build']
        branches:
            - master
        types:
            - completed

jobs:
    test:
        name: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run tests
              run: |
                  cd tests
                  mkdir build
                  cd build
                  cmake ..
                  make lzw_test
                  ./lzw_test
